/*
 * Copyright (C) 2020. Jacob Sandin och imCode Partner AB - All Rights Reserved.
 * This file is part of the project dbanonymizer., and you may use, distribute and modify this code under the licence agreement terms you have with imCode Partner AB for the specific project.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 08:14:17 PM CEST 
//


package com.imcode.internal.imAnonymizer.parser.xml;

import com.imcode.internal.imAnonymizer.log;
import org.apache.commons.lang3.StringUtils;

//import java.io.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="properties"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="jdbcDriver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="jdbcUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dbusername" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dbpassword" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="resources"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="files"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="file" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="statics"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="static" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tables"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="table" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="idfield" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="fields"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="field" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                                 &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "properties",
        "resources",
        "tables"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected Root.Properties properties;
    @XmlElement(required = true)
    protected Root.Resources resources;
    @XmlElement(required = true)
    protected Root.Tables tables;

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link Root.Properties }
     */
    public Root.Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     *              {@link Root.Properties }
     */
    public void setProperties(Root.Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the resources property.
     *
     * @return possible object is
     * {@link Root.Resources }
     */
    public Root.Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     *
     * @param value allowed object is
     *              {@link Root.Resources }
     */
    public void setResources(Root.Resources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the tables property.
     *
     * @return possible object is
     * {@link Root.Tables }
     */
    public Root.Tables getTables() {
        return tables;
    }

    /**
     * Sets the value of the tables property.
     *
     * @param value allowed object is
     *              {@link Root.Tables }
     */
    public void setTables(Root.Tables value) {
        this.tables = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="jdbcDriver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="jdbcUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dbusername" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dbpassword" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "jdbcDriver",
            "jdbcUrl",
            "dbusername",
            "dbpassword"
    })
    public static class Properties {

        @XmlElement(required = true)
        protected String jdbcDriver;
        @XmlElement(required = true)
        protected String jdbcUrl;
        @XmlElement(required = true)
        protected String dbusername;
        @XmlElement(required = true)
        protected String dbpassword;

        /**
         * Gets the value of the jdbcDriver property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getJdbcDriver() {
            return jdbcDriver;
        }

        /**
         * Sets the value of the jdbcDriver property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setJdbcDriver(String value) {
            this.jdbcDriver = value;
        }

        /**
         * Gets the value of the jdbcUrl property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getJdbcUrl() {
            return jdbcUrl;
        }

        /**
         * Sets the value of the jdbcUrl property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setJdbcUrl(String value) {
            this.jdbcUrl = value;
        }

        /**
         * Gets the value of the dbusername property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDbusername() {
            return dbusername;
        }

        /**
         * Sets the value of the dbusername property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDbusername(String value) {
            this.dbusername = value;
        }

        /**
         * Gets the value of the dbpassword property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDbpassword() {
            return dbpassword;
        }

        /**
         * Sets the value of the dbpassword property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDbpassword(String value) {
            this.dbpassword = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="files"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="file" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="statics"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="static" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "files",
            "statics"
    })
    public static class Resources {

        @XmlElement(required = true)
        protected Root.Resources.Files files;
        @XmlElement(required = true)
        protected Root.Resources.Statics statics;

        /**
         * Gets the value of the files property.
         *
         * @return possible object is
         * {@link Root.Resources.Files }
         */
        public Root.Resources.Files getFiles() {
            return files;
        }

        /**
         * Sets the value of the files property.
         *
         * @param value allowed object is
         *              {@link Root.Resources.Files }
         */
        public void setFiles(Root.Resources.Files value) {
            this.files = value;
        }

        /**
         * Gets the value of the statics property.
         *
         * @return possible object is
         * {@link Root.Resources.Statics }
         */
        public Root.Resources.Statics getStatics() {
            return statics;
        }

        /**
         * Sets the value of the statics property.
         *
         * @param value allowed object is
         *              {@link Root.Resources.Statics }
         */
        public void setStatics(Root.Resources.Statics value) {
            this.statics = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="file" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "file"
        })
        public static class Files {

            protected List<Root.Resources.Files.File> file;

            /**
             * Gets the value of the file property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the file property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFile().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Root.Resources.Files.File }
             */
            public List<Root.Resources.Files.File> getFile() {
                if (file == null) {
                    file = new ArrayList<Root.Resources.Files.File>();
                }
                return this.file;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "alias",
                    "file"
            })
            public static class File {

                @XmlElement(required = true)
                protected String alias;
                @XmlElement(required = true)
                protected String file;

                /**
                 * Gets the value of the alias property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getAlias() {
                    return alias;
                }

                /**
                 * Sets the value of the alias property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setAlias(String value) {
                    this.alias = value;
                }

                /**
                 * Gets the value of the file property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getFile() {
                    return file;
                }

                /**
                 * Sets the value of the file property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setFile(String value) {
                    this.file = value;
                }

                //TODO: This function should be moved as it is a autogenerated file.
                public String getProcessedValue() {
                    FileInputStream fs = null;
                    try {
                        fs = new FileInputStream(file);
                        BufferedReader br = new BufferedReader(new InputStreamReader(fs,"UTF8"));
                        ArrayList<String> array = new ArrayList<>();
                        String line;
                        while (true) {
                            if (!((line = br.readLine()) != null)) break;
                            array.add(line);
                        }
                        // variable so that it is not re-seeded every call.
                        Random rand = new Random();

                        // nextInt is exclusive. Should be good with output for array.
                        int randomIndex = rand.nextInt(array.size());

                        // Print your random quote...
                        //log.debug(array.get(randomIndex));
                        return "'"+array.get(randomIndex)+"'";
                    } catch (FileNotFoundException e) {
                        log.debug(e);
                    } catch (IOException e) {
                        log.debug(e);
                    }
                    return "";
                }
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="static" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "_static"
        })
        public static class Statics {

            @XmlElement(name = "static")
            protected List<Root.Resources.Statics.Static> _static;

            /**
             * Gets the value of the static property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the static property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStatic().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Root.Resources.Statics.Static }
             */
            public List<Root.Resources.Statics.Static> getStatic() {
                if (_static == null) {
                    _static = new ArrayList<Root.Resources.Statics.Static>();
                }
                return this._static;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "alias",
                    "value"
            })
            public static class Static {

                @XmlElement(required = true)
                protected String alias;
                @XmlElement(required = true)
                protected String value;

                /**
                 * Gets the value of the alias property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getAlias() {
                    return alias;
                }

                /**
                 * Sets the value of the alias property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setAlias(String value) {
                    this.alias = value;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                //TODO: This function should be moved as it is a autogenerated file.
                public String getProcessedValue() {
                    if (value.equals("nothing")) {
                        return "NULL";
                    }
                    return value;
                }
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="table" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="idfield" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="fields"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="field" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "table"
    })
    public static class Tables {

        protected List<Root.Tables.Table> table;

        /**
         * Gets the value of the table property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the table property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTable().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Root.Tables.Table }
         */
        public List<Root.Tables.Table> getTable() {
            if (table == null) {
                table = new ArrayList<Root.Tables.Table>();
            }
            return this.table;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="idfield" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="fields"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="field" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "name",
                "idfield",
                "fields"
        })
        public static class Table {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String idfield;
            @XmlElement(required = true)
            protected Root.Tables.Table.Fields fields;

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the idfield property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdfield() {
                return idfield;
            }

            /**
             * Sets the value of the idfield property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdfield(String value) {
                this.idfield = value;
            }

            /**
             * Gets the value of the fields property.
             *
             * @return possible object is
             * {@link Root.Tables.Table.Fields }
             */
            public Root.Tables.Table.Fields getFields() {
                return fields;
            }

            /**
             * Sets the value of the fields property.
             *
             * @param value allowed object is
             *              {@link Root.Tables.Table.Fields }
             */
            public void setFields(Root.Tables.Table.Fields value) {
                this.fields = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="field" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "field"
            })
            public static class Fields {

                protected List<Root.Tables.Table.Fields.Field> field;

                /**
                 * Gets the value of the field property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the field property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getField().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Root.Tables.Table.Fields.Field }
                 */
                public List<Root.Tables.Table.Fields.Field> getField() {
                    if (field == null) {
                        field = new ArrayList<Root.Tables.Table.Fields.Field>();
                    }
                    return this.field;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
                 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "name",
                        "_if",
                        "value"
                })
                public static class Field {

                    @XmlElement(required = true)
                    protected String name;
                    @XmlElement(name = "if")
                    protected String _if;
                    @XmlElement(required = true)
                    protected String value;

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the if property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getIf() {
                        return _if;
                    }

                    /**
                     * Sets the value of the if property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setIf(String value) {
                        this._if = value;
                    }

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    public boolean ValidateChange(String fieldValue) {
                        if ((fieldValue==null || StringUtils.isBlank(fieldValue))
                                && (_if != null && _if.equals("notempty")))
                                {return false;}
                        return true;
                    }
                }

            }

        }

    }

}
